# Generated by Django 2.1.5 on 2019-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_data', models.DateField(verbose_name='date published')),
                ('end_data', models.DateField(verbose_name='date published')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
