# Generated by Django 2.1.5 on 2019-01-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislature',
            name='year',
            field=models.IntegerField(default=1918),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legislature',
            name='end_data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='legislature',
            name='start_data',
            field=models.DateField(blank=True),
        ),
    ]
