# Generated by Django 2.1.5 on 2019-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatures', '0002_auto_20190127_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislature',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
