# Generated by Django 2.1.5 on 2019-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatures', '0003_auto_20190127_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislature',
            name='end_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislature',
            name='start_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
