# Generated by Django 2.1.5 on 2019-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatures', '0007_make_numbers_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislature',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
