# Generated by Django 2.1.7 on 2019-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatures', '0008_legislature_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarygroup',
            name='colour_code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
